services:
  - type: web
    name: reportup-pdf-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PDF_SECRET
        generateValue: true
